mpiexec -n 1 python mandelbrot-parallel.py | fgrep "csv,parallel"
mpiexec -n 2 python mandelbrot-parallel.py | fgrep "csv,parallel"
mpiexec -n 3 python mandelbrot-parallel.py | fgrep "csv,parallel"
mpiexec -n 4 python mandelbrot-parallel.py | fgrep "csv,parallel"
mpiexec -n 5 python mandelbrot-parallel.py | fgrep "csv,parallel"
mpiexec -n 6 python mandelbrot-parallel.py | fgrep "csv,parallel"
mpiexec -n 7 python mandelbrot-parallel.py | fgrep "csv,parallel"
mpiexec -n 8 python mandelbrot-parallel.py | fgrep "csv,parallel"
