FROM pandoc/latex:latest

# Install bash
RUN apk update
RUN apk upgrade
RUN apk add bash

# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

# Install pandoc-include

RUN pip install pandoc-include

RUN apk add texmf-dist texlive-full
RUN wget http://mirror.ctan.org/systems/texlive/tlnet/update-tlmgr-latest.sh
RUN sh update-tlmgr-latest.sh


#RUN apk add texlive-bibtexextra
RUN apk add biber


RUN tlmgr update --all --self
RUN tlmgr install tcolorbox
RUN tlmgr install pgf
RUN tlmgr install xcolor
RUN tlmgr install environ
RUN tlmgr install trimspaces
RUN tlmgr install mathpazo
RUN tlmgr install parskip
RUN tlmgr install adjustbox
RUN tlmgr install collectbox
RUN tlmgr install eurosym
RUN tlmgr install ucs
RUN tlmgr install enumitem
RUN tlmgr install jknapltx rsfs
RUN tlmgr install collection-fontsrecommended
RUN tlmgr install titling

RUN apk add make
RUN apk add git
RUN apk add ghc
# RUN pip install --upgrade --force --no-cache git+https://github.com/DCsunset/pandoc-include
RUN apk add cabal
RUN cabal update
RUN cabal install pandoc-include-code
