USER=gregor
NODE=i5
NODE=alienware


i5:
	papermill sweep.ipynb sweep-gregor-${NODE}-2.ipynb -p user ${USER} -p node ${NODE} -p processors 2
	papermill sweep.ipynb sweep-gregor-${NODE}-3.ipynb -p user ${USER} -p node ${NODE} -p processors 3
	papermill sweep.ipynb sweep-gregor-${NODE}-4.ipynb -p user ${USER} -p node ${NODE} -p processors 4
	papermill sweep.ipynb sweep-gregor-${NODE}-5.ipynb -p user ${USER} -p node ${NODE} -p processors 5
	papermill sweep.ipynb sweep-gregor-${NODE}-6.ipynb -p user ${USER} -p node ${NODE} -p processors 6
	papermill sweep.ipynb sweep-gregor-${NODE}-7.ipynb -p user ${USER} -p node ${NODE} -p processors 7
	papermill sweep.ipynb sweep-gregor-${NODE}-8.ipynb -p user ${USER} -p node ${NODE} -p processors 8
	papermill sweep.ipynb sweep-gregor-${NODE}-9.ipynb -p user ${USER} -p node ${NODE} -p processors 9
	papermill sweep.ipynb sweep-gregor-${NODE}-10.ipynb -p user ${USER} -p node ${NODE} -p processors 10
	papermill sweep.ipynb sweep-gregor-${NODE}-11.ipynb -p user ${USER} -p node ${NODE} -p processors 11
	papermill sweep.ipynb sweep-gregor-${NODE}-12.ipynb -p user ${USER} -p node ${NODE} -p processors 12


alienware:
	papermill sweep.ipynb sweep-gregor-${NODE}-2.ipynb -p user ${USER} -p node ${NODE} -p processors 2
	#papermill sweep.ipynb sweep-gregor-${NODE}-3.ipynb -p user ${USER} -p node ${NODE} -p processors 3
	papermill sweep.ipynb sweep-gregor-${NODE}-4.ipynb -p user ${USER} -p node ${NODE} -p processors 4
	#papermill sweep.ipynb sweep-gregor-${NODE}-5.ipynb -p user ${USER} -p node ${NODE} -p processors 5
	#papermill sweep.ipynb sweep-gregor-${NODE}-6.ipynb -p user ${USER} -p node ${NODE} -p processors 6
	#papermill sweep.ipynb sweep-gregor-${NODE}-7.ipynb -p user ${USER} -p node ${NODE} -p processors 7
	papermill sweep.ipynb sweep-gregor-${NODE}-8.ipynb -p user ${USER} -p node ${NODE} -p processors 8
	#papermill sweep.ipynb sweep-gregor-${NODE}-9.ipynb -p user ${USER} -p node ${NODE} -p processors 9
	#papermill sweep.ipynb sweep-gregor-${NODE}-10.ipynb -p user ${USER} -p node ${NODE} -p processors 10
	#papermill sweep.ipynb sweep-gregor-${NODE}-11.ipynb -p user ${USER} -p node ${NODE} -p processors 11
	papermill sweep.ipynb sweep-gregor-${NODE}-12.ipynb -p user ${USER} -p node ${NODE} -p processors 12
	papermill sweep.ipynb sweep-gregor-${NODE}-12.ipynb -p user ${USER} -p node ${NODE} -p processors 16
	papermill sweep.ipynb sweep-gregor-${NODE}-12.ipynb -p user ${USER} -p node ${NODE} -p processors 24
	papermill sweep.ipynb sweep-gregor-${NODE}-12.ipynb -p user ${USER} -p node ${NODE} -p processors 28
	papermill sweep.ipynb sweep-gregor-${NODE}-12.ipynb -p user ${USER} -p node ${NODE} -p processors 32
