USER=gregor
NODE=i5

all:
	papermill sweep.ipynb sweep-gregor-i5-2.ipynb -p user ${USER} -p node ${NODE} -p processors 2
	papermill sweep.ipynb sweep-gregor-i5-3.ipynb -p user ${USER} -p node ${NODE} -p processors 3
	papermill sweep.ipynb sweep-gregor-i5-4.ipynb -p user ${USER} -p node ${NODE} -p processors 4
	papermill sweep.ipynb sweep-gregor-i5-5.ipynb -p user ${USER} -p node ${NODE} -p processors 5
	papermill sweep.ipynb sweep-gregor-i5-6.ipynb -p user ${USER} -p node ${NODE} -p processors 6
	papermill sweep.ipynb sweep-gregor-i5-7.ipynb -p user ${USER} -p node ${NODE} -p processors 7
	papermill sweep.ipynb sweep-gregor-i5-8.ipynb -p user ${USER} -p node ${NODE} -p processors 8
	papermill sweep.ipynb sweep-gregor-i5-9.ipynb -p user ${USER} -p node ${NODE} -p processors 9
	papermill sweep.ipynb sweep-gregor-i5-10.ipynb -p user ${USER} -p node ${NODE} -p processors 10
	papermill sweep.ipynb sweep-gregor-i5-11.ipynb -p user ${USER} -p node ${NODE} -p processors 11
	papermill sweep.ipynb sweep-gregor-i5-12.ipynb -p user ${USER} -p node ${NODE} -p processors 12
