USER=gregor
NODE=i5
NODE=alienware

alienware:
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-1.ipynb -p user ${USER} -p node ${NODE} -p processors 1
	#papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-2.ipynb -p user ${USER} -p node ${NODE} -p processors 2
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-3.ipynb -p user ${USER} -p node ${NODE} -p processors 3
	##papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-4.ipynb -p user ${USER} -p node ${NODE} -p processors 4
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-5.ipynb -p user ${USER} -p node ${NODE} -p processors 5
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-6.ipynb -p user ${USER} -p node ${NODE} -p processors 6
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-7.ipynb -p user ${USER} -p node ${NODE} -p processors 7
	##papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-8.ipynb -p user ${USER} -p node ${NODE} -p processors 8
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-9.ipynb -p user ${USER} -p node ${NODE} -p processors 9
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-10.ipynb -p user ${USER} -p node ${NODE} -p processors 10
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-11.ipynb -p user ${USER} -p node ${NODE} -p processors 11
	##papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-12.ipynb -p user ${USER} -p node ${NODE} -p processors 12
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-13.ipynb -p user ${USER} -p node ${NODE} -p processors 13
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-14.ipynb -p user ${USER} -p node ${NODE} -p processors 14
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-15.ipynb -p user ${USER} -p node ${NODE} -p processors 15
	##papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-16.ipynb -p user ${USER} -p node ${NODE} -p processors 16
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-17.ipynb -p user ${USER} -p node ${NODE} -p processors  17
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-18.ipynb -p user ${USER} -p node ${NODE} -p processors  18
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-19.ipynb -p user ${USER} -p node ${NODE} -p processors  19
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-20.ipynb -p user ${USER} -p node ${NODE} -p processors  20
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-21.ipynb -p user ${USER} -p node ${NODE} -p processors  21
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-22.ipynb -p user ${USER} -p node ${NODE} -p processors  22
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-23.ipynb -p user ${USER} -p node ${NODE} -p processors  23
	##papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-24.ipynb -p user ${USER} -p node ${NODE} -p processors 24
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-25.ipynb -p user ${USER} -p node ${NODE} -p processors  25
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-26.ipynb -p user ${USER} -p node ${NODE} -p processors  26
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-27.ipynb -p user ${USER} -p node ${NODE} -p processors  27
	##papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-28.ipynb -p user ${USER} -p node ${NODE} -p processors 28
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-29.ipynb -p user ${USER} -p node ${NODE} -p processors  29
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-30.ipynb -p user ${USER} -p node ${NODE} -p processors  30
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-31.ipynb -p user ${USER} -p node ${NODE} -p processors 31
	##papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-32.ipynb -p user ${USER} -p node ${NODE} -p processors 32

i5:
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-1.ipynb -p user ${USER} -p node ${NODE} -p processors 1
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-2.ipynb -p user ${USER} -p node ${NODE} -p processors 2
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-3.ipynb -p user ${USER} -p node ${NODE} -p processors 3
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-4.ipynb -p user ${USER} -p node ${NODE} -p processors 4
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-5.ipynb -p user ${USER} -p node ${NODE} -p processors 5
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-6.ipynb -p user ${USER} -p node ${NODE} -p processors 6
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-7.ipynb -p user ${USER} -p node ${NODE} -p processors 7
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-8.ipynb -p user ${USER} -p node ${NODE} -p processors 8
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-9.ipynb -p user ${USER} -p node ${NODE} -p processors 9
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-10.ipynb -p user ${USER} -p node ${NODE} -p processors 10
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-11.ipynb -p user ${USER} -p node ${NODE} -p processors 11
	papermill sweep.ipynb benchmark/${USER}/sweep-${USER}-${NODE}-12.ipynb -p user ${USER} -p node ${NODE} -p processors 12


